/* groovylint-disable-next-line CompileStatic */
job('First-Maven-Project-Via-DSL101') {
    /* groovylint-disable-next-line LineLength */
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/MahbubAhmedTonmoy/jenkins-learn.git", '*/main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts('**/*.jar')
    }
}
